# Generated by Django 2.2.5 on 2019-09-13 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20180522_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='max_length',
            field=models.IntegerField(blank=True, help_text='Limit maximum length below the default of 2000.', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)], verbose_name='Max length'),
        ),
    ]
