# Generated by Django 2.2.5 on 2019-09-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_field_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='choices',
            field=models.CharField(blank=True, help_text='Comma separated options where applicable. If an option itself contains commas, surround the option starting with the `character and ending with the ` character.', max_length=2000, verbose_name='Choices'),
        ),
        migrations.AlterField(
            model_name='field',
            name='help_text',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Help text'),
        ),
    ]
